package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// ExecutionTask represents a single step in the conversion pipeline.
type ExecutionTask struct {
	ID         string            `json:"id"`
	InputPath  string            `json:"inputPath"`
	OutputPath string            `json:"outputPath"`
	Command    string            `json:"command"`
	Args       []string          `json:"args"`
	Env        map[string]string `json:"env,omitempty"`
	StepType   string            `json:"stepType"`
}

// ExecutionPlan is generated by the frontend and consumed by the backend.
type ExecutionPlan struct {
	RunID     string          `json:"runId"`
	Items     []FileItem      `json:"items"`
	Tasks     []ExecutionTask `json:"tasks"`
	Policies  ResultPolicy    `json:"policies"`
	Toolchain ToolchainPaths  `json:"toolchain"`
	Spec      *ExecutionSpec  `json:"spec,omitempty"`
}

// ResultPolicy defines post-processing decisions.
type ResultPolicy struct {
	KeepIfLarger     bool   `json:"keepIfLarger"`
	CopyIfLarger     bool   `json:"copyIfLarger"`
	DeleteOriginal   bool   `json:"deleteOriginal"`
	DeleteOriginalMode string `json:"deleteOriginalMode"`
	KeepTimestamps   bool   `json:"keepTimestamps"`
	IfFileExists     string `json:"ifFileExists"`
}

// ToolchainPaths maps tool names to binary paths.
type ToolchainPaths struct {
	CJXLPath        string `json:"cjxlPath"`
	DJXLPath        string `json:"djxlPath"`
	AvifEncPath     string `json:"avifencPath"`
	AvifDecPath     string `json:"avifdecPath"`
	CJPEGLIPath     string `json:"cjpegliPath"`
	ImageMagickPath string `json:"imagemagickPath"`
	ExifToolPath    string `json:"exiftoolPath"`
	OxiPNGPath      string `json:"oxipngPath"`
}

// runExecutionPlan executes a frontend-generated plan.
func runExecutionPlan(ctx context.Context, plan ExecutionPlan, threadCount int) {
	total := len(plan.Items)
	if total == 0 {
		return
	}

	var completed atomic.Int32
	startTime := time.Now()

	maxConcurrent := threadCount
	sem := make(chan struct{}, maxConcurrent)
	var wg sync.WaitGroup

	App.Event.Emit("conversion:started", struct{}{})

	for i, item := range plan.Items {
		if GlobalTaskStatus.WasCanceled() {
			break
		}

		sem <- struct{}{}
		wg.Add(1)

		go func(idx int, fi FileItem) {
			defer func() {
				<-sem
				wg.Done()
			}()

			if GlobalTaskStatus.WasCanceled() {
				return
			}

			srcSize, dstSize, skipped, exc := runItemTasks(ctx, fi, plan, threadCount)

			if exc != nil {
				App.Event.Emit("conversion:exception", ExceptionEvent{
					ID:   exc.id,
					Msg:  exc.msg,
					Path: fi.AbsPath,
				})
			}

			n := completed.Add(1)

			if !skipped {
				line1 := ""
				if srcSize > 0 && dstSize > 0 {
					srcStr := formatSize(srcSize)
					dstStr := formatSize(dstSize)
					pct := float64(srcSize-dstSize) / float64(srcSize) * 100
					pctStr := fmt.Sprintf("-%.0f%%", pct)
					if pct < 0 {
						pctStr = fmt.Sprintf("+%.0f%%", -pct)
					}
					line1 = fmt.Sprintf("%s : %s → %s (%s)", filepath.Base(fi.AbsPath), srcStr, dstStr, pctStr)
				} else {
					line1 = fmt.Sprintf("Converted %d out of %d images", n, total)
				}

				elapsed := time.Since(startTime)
				remaining := time.Duration(0)
				if n > 0 {
					perItem := elapsed / time.Duration(n)
					remaining = perItem * time.Duration(total-int(n))
				}
				line2 := formatTimeLeft(remaining)

				App.Event.Emit("conversion:progress", ProgressEvent{
					Completed: int(n),
					Total:     total,
					Line1:     line1,
					Line2:     line2,
				})
			}
		}(i, item)
	}

	wg.Wait()
}

// runItemTasks executes all tasks for a single file item.
func runItemTasks(ctx context.Context, fi FileItem, plan ExecutionPlan, threadCount int) (int64, int64, bool, *conversionError) {
	// Find tasks belonging to this item
	itemTasks := filterTasksForItem(plan.Tasks, fi.AbsPath)
	if len(itemTasks) == 0 {
		return 0, 0, false, &conversionError{"C0", "No tasks for item"}
	}

	srcSize, _ := getFileSize(fi.AbsPath)

	var finalOutput string
	var firstEncodeOutput string

	for _, task := range itemTasks {
		if task.StepType == "encode" {
			firstEncodeOutput = task.OutputPath
			break
		}
	}

	if plan.Policies.IfFileExists == "Skip" && firstEncodeOutput != "" {
		if _, err := os.Stat(firstEncodeOutput); err == nil {
			return srcSize, 0, true, nil
		}
	}

	for _, task := range itemTasks {
		if GlobalTaskStatus.WasCanceled() {
			return srcSize, 0, false, &conversionError{"X0", "Canceled"}
		}

		if task.StepType == "cleanup" {
			if err := os.Remove(task.OutputPath); err != nil && !os.IsNotExist(err) {
				return srcSize, 0, false, &conversionError{"S1", fmt.Sprintf("Failed to clean up temporary file: %s", err)}
			}
			continue
		}

		// Resolve command path from toolchain if relative
		cmdPath := resolveCommandPath(task.Command, plan.Toolchain)
		if cmdPath == "" {
			return srcSize, 0, false, &conversionError{"C4", fmt.Sprintf("Command not found: %s", task.Command)}
		}

		// Create output directory
		outDir := filepath.Dir(task.OutputPath)
		if err := os.MkdirAll(outDir, 0755); err != nil {
			return srcSize, 0, false, &conversionError{"S0", fmt.Sprintf("Failed to create output directory: %s", err)}
		}

		// Build args: replace input/output placeholders if any
		args := make([]string, len(task.Args))
		copy(args, task.Args)

		// Run the task
		_, stderr, err := runTaskCommand(ctx, cmdPath, args, task.Env)
		if err != nil {
			if GlobalTaskStatus.WasCanceled() {
				return srcSize, 0, false, &conversionError{"X0", "Canceled"}
			}
			return srcSize, 0, false, &conversionError{"C3", fmt.Sprintf("[%s] %s", filepath.Base(cmdPath), stderr)}
		}

		if task.StepType == "encode" || task.StepType == "metadata" {
			finalOutput = task.OutputPath
		}
	}

	if finalOutput == "" {
		return srcSize, 0, false, &conversionError{"C0", "No output produced"}
	}

	// Apply result policies
	dstSize, _ := getFileSize(finalOutput)

	keepOriginal := false
	if plan.Policies.KeepIfLarger && dstSize >= srcSize {
		_ = os.Remove(finalOutput)
		keepOriginal = true
	} else if plan.Policies.CopyIfLarger && dstSize >= srcSize {
		_ = os.Remove(finalOutput)
		_ = os.Rename(fi.AbsPath, finalOutput)
		keepOriginal = true
	}

	// Apply timestamps
	if plan.Policies.KeepTimestamps && !keepOriginal {
		if info, statErr := os.Stat(fi.AbsPath); statErr == nil {
			_ = os.Chtimes(finalOutput, info.ModTime(), info.ModTime())
		}
	}

	// Delete original
	if plan.Policies.DeleteOriginal && !keepOriginal {
		if plan.Policies.DeleteOriginalMode == "To Trash" {
			_ = moveToTrash(fi.AbsPath)
		} else {
			_ = os.Remove(fi.AbsPath)
		}
	}

	return srcSize, dstSize, false, nil
}

func filterTasksForItem(tasks []ExecutionTask, itemPath string) []ExecutionTask {
	var result []ExecutionTask
	for _, t := range tasks {
		if t.InputPath == itemPath || strings.Contains(t.ID, itemPath) {
			result = append(result, t)
		}
	}
	return result
}

func resolveCommandPath(cmd string, toolchain ToolchainPaths) string {
	// If it's already an absolute path, use it directly
	if filepath.IsAbs(cmd) {
		return cmd
	}

	// Map common command names to toolchain paths
	switch strings.ToLower(cmd) {
	case "cjxl":
		return toolchain.CJXLPath
	case "djxl":
		return toolchain.DJXLPath
	case "avifenc":
		return toolchain.AvifEncPath
	case "avifdec":
		return toolchain.AvifDecPath
	case "cjpegli":
		return toolchain.CJPEGLIPath
	case "magick", "imagemagick":
		return toolchain.ImageMagickPath
	case "exiftool":
		return toolchain.ExifToolPath
	case "oxipng":
		return toolchain.OxiPNGPath
	}

	// Try to find in PATH
	if path, err := exec.LookPath(cmd); err == nil {
		return path
	}

	return ""
}

func runTaskCommand(ctx context.Context, cmdPath string, args []string, env map[string]string) (string, string, error) {
	cmd := exec.CommandContext(ctx, cmdPath, args...)

	if env != nil {
		for k, v := range env {
			cmd.Env = append(os.Environ(), k+"="+v)
		}
	}

	GlobalProcessManager.Add(cmd)
	defer GlobalProcessManager.Remove(cmd)

	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}
