// Domain models - pure data, host-agnostic

export interface FileItem {
  absPath: string;
  name: string;
  ext: string;
  dir: string;
  size: number;
  anchorPath?: string;
}

export interface OutputSettings {
  format: string;
  quality: number;
  lossless: boolean;
  max_compression: boolean;
  effort: number;
  intelligent_effort: boolean;
  jxl_modular: boolean;
  jxl_verify: boolean;
  jxl_normalize_enable: boolean;
  jxl_normalize_when: string;
  aom_av1_chroma_subsampling: string;
  jpegli_chroma_subsampling: string;
  jpg_chroma_subsampling: string;
  if_file_exists: string;
  custom_output_dir: boolean;
  custom_output_dir_path: string;
  keep_dir_struct: boolean;
  delete_original: boolean;
  delete_original_mode: string;
  smallest_format_pool: Record<string, boolean>;
  jxl_png_fallback: boolean;
  threads?: number;
}

export interface DownscaleSettings {
  enabled: boolean;
  mode: string;
  percent: number;
  width: number;
  height: number;
  file_size: number;
  shortest_side: number;
  longest_side: number;
  megapixels: number;
  resample: string;
}

export interface MiscSettings {
  keep_metadata: string;
  keep_timestamps: boolean;
}

export interface ModifySettings {
  downscaling: DownscaleSettings;
  misc: MiscSettings;
}

export interface AppSettings {
  theme: string;
  lane_max_width: number;
  custom_resampling: boolean;
  sorting_disabled: boolean;
  excluded_formats: string[];
  disable_downscaling_startup: boolean;
  disable_delete_startup: boolean;
  enable_jxl_effort_10: boolean;
  disable_progressive_jpegli: boolean;
  enable_custom_args: boolean;
  cjxl_args: string;
  avifenc_args: string;
  cjpegli_args: string;
  im_args: string;
  enable_quality_precision_snapping: boolean;
  jpg_encoder: string;
  jxl_auto_lossless_jpeg: boolean;
  ram_optimizer: string;
  ram_optimizer_rules: string;
  jxl_lossy_modular: boolean;
  jxl_int_effort: boolean;
  play_sound_on_finish: boolean;
  play_sound_on_finish_vol: number;
  keep_if_larger: boolean;
  copy_if_larger: boolean;
  exiftool_args: Record<string, string>;
  avif_encoder: string;
  avif_bit_depth: string;
  avif_aom_iq_tune: boolean;
  processing_order: string;
  lane_auto_fit: boolean;
  auto_clear_completed: boolean;
}

export interface ConversionSpec {
  output: OutputSettings;
  modify: ModifySettings;
  app: AppSettings;
}

export interface ExecutionSpec {
  output: OutputSettings;
  modify: ModifySettings;
  app: AppSettings;
}

export type BackgroundMode = 'dot-grid' | 'image' | 'none';

export interface BackgroundSettings {
  mode: BackgroundMode;
  imageUrl: string;
  opacity: number;
  blur: number;
}

export interface AppStateSnapshot {
  domain: ConversionSpec;
  layout: {
    laneOrder: string[];
    laneLabels: Record<string, string>;
    laneWidths: Record<string, number>;
    cardLayout: Record<string, string[]>;
    singleLaneMode: boolean;
    activeLaneId: string;
    progressCardConfig: ProgressCardConfig;
    collapsedLanes: string[];
    hiddenLanes: string[];
    hiddenCards: string[];
  };
  presets: Preset[];
  theme: {
    name: string;
    mode: 'light' | 'dark' | 'system';
    customThemes: CustomThemeConfig[];
  };
  background: BackgroundSettings;
  lang: string;
  executor: string;
}

export interface ProgressCardConfig {
  showCounter: boolean;
  showSummary: boolean;
  showEta: boolean;
  showFormat: boolean;
  showEncoder: boolean;
  showRawLines: boolean;
  showCurrentFile: boolean;
  showSizeChange: boolean;
}

export interface CustomThemeConfig {
  name: string;
  description: string;
  colors: { light: any; dark: any };
}

export interface Preset {
  name: string;
  output: OutputSettings;
  modify: ModifySettings;
  app: Partial<AppSettings>;
}

// Execution plan - generated by frontend, consumed by executor
export interface ExecutionTask {
  id: string;
  inputPath: string;
  outputPath: string;
  command: string;
  args: string[];
  env?: Record<string, string>;
  stepType: 'decode' | 'downscale' | 'encode' | 'metadata' | 'cleanup';
}

export interface ExecutionPlan {
  runId: string;
  items: FileItem[];
  tasks: ExecutionTask[];
  policies: ResultPolicy;
  toolchain: ToolchainSelection;
  spec?: ExecutionSpec;
}

export interface ResultPolicy {
  keepIfLarger: boolean;
  copyIfLarger: boolean;
  deleteOriginal: boolean;
  deleteOriginalMode: string;
  keepTimestamps: boolean;
  ifFileExists: string;
}

export interface ToolchainSelection {
  cjxlPath: string;
  djxlPath: string;
  avifencPath: string;
  avifdecPath: string;
  cjpegliPath: string;
  imagemagickPath: string;
  exiftoolPath: string;
  oxipngPath: string;
}

// Unified events - host-agnostic
export interface RunStartedEvent {
  type: 'run_started';
  runId: string;
  totalTasks: number;
}

export interface TaskProgressEvent {
  type: 'task_progress';
  runId: string;
  taskId: string;
  completed: number;
  total: number;
  line1: string;
  line2: string;
}

export interface TaskSucceededEvent {
  type: 'task_succeeded';
  runId: string;
  taskId: string;
  inputPath: string;
  outputPath: string;
  srcSize: number;
  dstSize: number;
}

export interface TaskFailedEvent {
  type: 'task_failed';
  runId: string;
  taskId: string;
  inputPath: string;
  errorId: string;
  errorMsg: string;
}

export interface RunFinishedEvent {
  type: 'run_finished';
  runId: string;
  completedCount: number;
  failedCount: number;
}

export interface RunCanceledEvent {
  type: 'run_canceled';
  runId: string;
}

export interface FilesDroppedEvent {
  type: 'files_dropped';
  paths: string[];
}

export type DomainEvent =
  | RunStartedEvent
  | TaskProgressEvent
  | TaskSucceededEvent
  | TaskFailedEvent
  | RunFinishedEvent
  | RunCanceledEvent
  | FilesDroppedEvent;

export interface AppConstants {
  version: string;
  allowedInput: string[];
  allowedResampling: string[];
  allowedInputFilters: string[];
  jpegAliases: string[];
  cpuCount: number;
  updateCheckerEnabled: boolean;
}
